version: '3.8'
services:
  graphhopper:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8989:8989"
    volumes:
      - graphhopper-data:/app/graph-cache
      - osm-data:/app/osm-data
    restart: unless-stopped

volumes:
  graphhopper-data:
    driver: local
    driver_opts:
      type: none
      device: /app/data
      o: bind
  osm-data:
    driver: local
    driver_opts:
      type: none
      device: /app/data
      o: bind